# Generated by Django 2.0.2 on 2018-03-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180303_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecontact',
            name='email',
            field=models.CharField(default='noname@mail.com', max_length=255),
        ),
    ]
